---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpass-secret
      mappingMethod: claim
      name: my_identity_provider
      type: HTPasswd
    - ldap:
        attributes:
          email: []
          id:
            - dn
          name:
            - cn
          preferredUsername:
            - uid
        bindDN: fds
        bindPassword:
          name: ldap-bind-password-2rt2g
        insecure: false
        url: 'ldap://fdsfs'
      mappingMethod: claim
      name: ldap
      type: LDAP
